Prefab rotation and reflection.
proletariatgames/vertexy pull request #7
Opened 2022-06-01 20:01 UTC by RenatoVog

-Adds a tile class. Now prefab is a matrix of tiles instead of integers.
-Adds rotation and reflection to prefab.
-Moves constrains creation from prefab to prefab manager, remove prefab dependency on prefab manager.
-createPrefab now allow rotation and reflection.
-Adds "PrefabTest-Rot/Refl" test.

2022-06-01 21:29 UTC, ViolinLloyd approved these changes

2022-06-07 14:12 UTC, dogles requested changes

2022-06-07 14:12 UTC, dogles commented on vertexy/src/private/prefab/PrefabManager.cpp
> +			);
minor: for style consistency, can you align the end-paren with the top of the statement

2022-06-07 14:12 UTC, dogles commented on vertexy/src/private/prefab/Tile.cpp
> +	vector<char> v = { 'X', 'I', '/', 'T', 'L', 'F' };
can you add a comment here what each letter represents

2022-06-07 14:59 UTC, dogles approved these changes

2022-06-07 14:59 UTC, merged